### ISSUE TITLE
pivot configuration : postcode instead of citycode

### ISSUE THREAD

**Issue by EtienneArbogast** [Mapotempo/addok-search2steps#1]
Hi, thanks for this useful add-on !
As addok is focused on the use of french adresses databases, shouldn't `SEARCH_2_STEPS_PIVOT_FILTER = 'postcode'` be used instead of `'citycode'` ?
From personal experience, it works a lot best :-)

**Comment by MrFenril** [comment]
Hi
It might be a bit late to give an answer but thank you for the comment.
Your idea was indeed interesting and gave me hints for the latest improvements.

**Comment by alain-andre** [comment]
I close, reopen if needed.
